"""The front door of a music company plays music.

The homepage had a "Hear the score" button in the hero — two lines under the promise
*"written and recorded in house by people — never AI-generated audio"* — and it scrolled
to a player driven by a **WebAudio oscillator**. Four synth voices through lowpass
filters. There was no `<audio>` element and no recording anywhere on the page; the only
match for `.mp3` in 2,000-odd lines was `o.type = t.wave`.

So a visitor who clicked the one button offering to let them hear the product heard a
machine, on the page that had just promised them the opposite.

Meanwhile four real capability demonstrations existed with audio attached and honest
framing ("demonstrations of approach/craft, not client commissions"), and
`showcase.DEMOS_INTRO` already carried a `home_title` / `home_cta` written for a homepage
section that was never built.

ADR-0040 builds it, and makes the synth say what it is.
"""

import os
import re
from pathlib import Path

import pytest

from chordential_oia.web.showcase import get_showcase

pytest.importorskip("fastapi")
pytest.importorskip("httpx")
from fastapi.testclient import TestClient  # noqa: E402

from chordential_oia.web import app as app_mod  # noqa: E402
from chordential_oia.web import public as _public  # noqa: E402

_STATIC = os.path.join(os.path.dirname(os.path.abspath(_public.__file__)),
                       "static", "public")

HOME = (Path(app_mod.__file__).parent / "templates"
        / "public" / "commission.html").read_text(encoding="utf-8")


@pytest.fixture()
def client():
    with TestClient(app_mod.app) as c:
        yield c


def _home(client):
    r = client.get("/")
    assert r.status_code == 200
    return r.text


# --------------------------------------------------------------------------- #
# There is music
# --------------------------------------------------------------------------- #
def test_the_homepage_has_real_audio(client):
    html = _home(client)
    srcs = re.findall(r'<audio[^>]*src="([^"]+)"', html)
    assert srcs, "the front door of a music company still plays no music"
    assert len(srcs) >= 4


def test_every_track_actually_serves_audio(client):
    """A player pointing at a 404 is worse than no player."""
    for src in re.findall(r'<audio[^>]*src="([^"]+)"', _home(client)):
        r = client.get(src)
        assert r.status_code == 200, f"{src} does not serve"
        assert r.headers["content-type"].startswith("audio/"), src
        assert len(r.content) > 100_000, f"{src} is too small to be a track"


def test_the_tracks_are_served_by_us_not_a_third_party(client):
    """The front door should not need an external host to make a sound."""
    for src in re.findall(r'<audio[^>]*src="([^"]+)"', _home(client)):
        assert src.startswith("/"), f"{src} is off-site"


def test_they_are_four_different_recordings(client):
    """Four cards playing one file would be its own dishonesty. Compared on the audio
    payload with the ID3 tag stripped, so different tags on identical audio cannot
    pass as different tracks."""
    import hashlib

    def payload(b):
        if b[:3] == b"ID3":
            n = ((b[6] & 0x7F) << 21) | ((b[7] & 0x7F) << 14) | ((b[8] & 0x7F) << 7) | (b[9] & 0x7F)
            b = b[10 + n:]
        return hashlib.sha256(b).hexdigest()

    srcs = re.findall(r'<audio[^>]*src="([^"]+)"', _home(client))
    hashes = {payload(client.get(s).content) for s in srcs}
    assert len(hashes) == len(srcs), "two cards on the homepage play the same recording"


# --------------------------------------------------------------------------- #
# The hero no longer contradicts itself
# --------------------------------------------------------------------------- #
def test_the_hero_listen_cta_leads_to_recordings(client):
    html = _home(client)
    hero = html.split("<!-- 1b")[0]
    m = re.search(r'<a class="btn" href="(#[^"]+)">([^<]*)</a>', hero)
    assert m, "the hero lost its listen CTA"
    target, label = m.group(1), m.group(2)
    assert target == "#work", f"the listen CTA points at {target}, not the recordings"
    section = html.split('id="work"')[1].split("</section>")[0]
    assert "<audio" in section, "the CTA lands somewhere with no music"
    assert "score" not in label.lower(), (
        "the label still promises 'the score' — the synth is not the score")


def test_the_placeholder_audio_is_disclosed_where_it_plays(client):
    """The recordings on this site are AI-generated placeholders — every served demo
    carries the ID3 artist tag "Generated by ACE Studio", readable with a right-click
    in any player. The page used to promise "never AI-generated audio" two lines
    above them: true of what we DELIVER, false of what the page PLAYS, and a visitor
    cannot tell those apart from a hero.

    So this asserts the disclosure sits with the players, and that the promise is not
    reinstated over placeholder audio. Delete this test the day real sessions replace
    the placeholders — together with showcase.PLACEHOLDER_AUDIO_NOTICE, not before.
    """
    html = _home(client)
    assert "AI-generated placeholders" in html, (
        "the front door plays placeholder audio and does not say so")
    assert "never AI-generated audio" not in html, (
        "a human-authorship promise is back over AI-generated placeholder tracks")


def test_the_disclosure_is_one_string_on_every_surface_that_plays(client):
    """One derivation, many reporters. Three pages play these files; a disclosure
    maintained separately on each is one edit away from only being on two."""
    from chordential_oia.web.showcase import PLACEHOLDER_AUDIO_NOTICE
    for path in ("/", "/samples", "/showreel"):
        body = client.get(path).text
        assert PLACEHOLDER_AUDIO_NOTICE in body, f"{path} plays audio undisclosed"


def test_no_served_demo_claims_to_be_human_made_in_its_own_metadata():
    """The counterpart of the disclosure: if a file's tag is ever CHANGED to hide
    what it is, that is falsification, not a fix. This fails if a served track stops
    carrying the tag it currently carries without the notice coming down too."""
    import re
    from chordential_oia.web.showcase import get_showcase, PLACEHOLDER_AUDIO_NOTICE
    tagged = 0
    for demo in get_showcase().demos:
        if not (demo.audio_url or "").strip():
            continue
        path = os.path.join(_STATIC, os.path.basename(demo.audio_url))
        if not os.path.exists(path):
            continue
        head = open(path, "rb").read(8000)
        i = head.find(b"TPE1")
        if i > 0:
            size = int.from_bytes(head[i + 4:i + 8], "big")
            artist = head[i + 10:i + 10 + size].replace(b"\x00", b"")
            if b"Generated" in artist or b"ACE" in artist:
                tagged += 1
    if tagged:
        assert PLACEHOLDER_AUDIO_NOTICE, (
            "tracks self-describe as machine-generated but the notice is empty")


def test_the_synth_says_it_is_a_demonstration(client):
    """It is a good demo of the note mechanism and a bad impression of our music. It
    may stay, as long as it does not pass for a recording."""
    section = _home(client).split('id="take"')[1].split("</section>")[0]
    assert "generated by your browser" in section, (
        "the synth player still reads as though it were a recording")
    assert 'href="#work"' in section, "no route from the demo to the actual work"


# --------------------------------------------------------------------------- #
# One source for the tracks
# --------------------------------------------------------------------------- #
def test_the_home_section_and_samples_render_the_same_records(client):
    """Two pages describing the same track differently is the drift this session has
    been removing everywhere else."""
    demos = [d for d in get_showcase().demos if d.audio_url]
    assert demos, "no demo carries audio"
    home, samples = _home(client), client.get("/samples").text
    for d in demos:
        assert d.audio_url in home, f"{d.title} is missing from the homepage"
        assert d.audio_url in samples, f"{d.title} is missing from /samples"


def test_the_homepage_does_not_hardcode_a_track():
    """The section renders from showcase; swapping a file must not need a template
    edit. A literal .mp3 in the template is how the two pages would drift."""
    assert ".mp3" not in HOME


def test_the_demos_are_framed_as_demonstrations(client):
    """Honesty rule: never imply real client work. These answer briefs we set
    ourselves, and the page has to say so where the play buttons are."""
    section = _home(client).split('id="work"')[1].split("</section>")[0]
    assert "demonstration" in section.lower()
    assert "not a client" in section.lower() or "not client" in section.lower()


def test_the_section_offers_the_way_deeper(client):
    section = _home(client).split('id="work"')[1].split("</section>")[0]
    assert 'href="/samples"' in section


def test_it_degrades_without_javascript():
    """The recordings use the native control on purpose — the section's job is to get
    music playing, not to be another mechanism that can fail."""
    work = HOME.split('id="work"')[1].split("</section>")[0]
    assert "controls" in work, "the players depend on custom JS to be operable"
    assert "<script" not in work
