"""The release clause 6A obliged composers to collect, which did not exist.

The Composer Agreement tells a writer to get a signed release from anyone who performed,
sang, programmed, produced, engineered or co-wrote — *"paid or unpaid, stranger or
friend, in the room or over the internet"*. A council review then grepped for that
release and found **zero matches outside the agreement text**. The studio was asking
composers to collect a document nobody had written, which is worse than not asking: it
reads as diligence and delivers none.

This is the gap most likely to actually void a Clearance Certificate, and it needs no bad
faith. `delivery._contributors` builds the certificate's chain of title from ASSIGNMENTS
— operator records — so a violinist the composer booked for two hours is invisible to it.
In the UK it is sharper still: performers' rights under CDPA 1988 Part II are a separate
property right the composer cannot assign on the performer's behalf.
"""
import importlib

import pytest

from chordential_oia import contributor_release
from chordential_oia.signing import DOC_CONTRIBUTOR_RELEASE, document_digest

pytest.importorskip("fastapi")


# ── the document ─────────────────────────────────────────────────────────────────────
def _rel(**kw):
    base = dict(contributor="Ana Ruiz", role="Vocalist",
                work="Winter appeal film — topline", booked_by="Dale Malleh")
    base.update(kw)
    return contributor_release.build_release(**base)


def test_it_assigns_the_performance_and_the_recording():
    text = _rel().signable_text()
    assert "You assign to Chordential" in text
    assert "full term of copyright and throughout the world" in text
    assert "all rights in your performance and in the recording of it" in text


def test_it_warrants_the_performance_is_human_and_uncopied():
    """The two things that make the certificate's claim true, asked of the person who
    actually knows."""
    text = _rel().signable_text()
    assert "performed by you, a human being" in text
    assert "not generated by an artificial-intelligence music system" in text
    assert "did not use, quote or sample anyone else's recording" in text
    assert "telling us is never a problem" in text, (
        "disclosure must be the easy path or nobody discloses")


def test_it_waives_moral_rights_and_covers_union():
    text = _rel().signable_text()
    assert "waive your moral rights" in text
    assert "AFM" in text and "SAG-AFTRA" in text
    assert "no scale, pension, health" in text


def test_a_co_writer_gets_the_composition_clause_and_a_performer_does_not():
    """A co-writer contributes to the WORK, not only the recording — and is told, in the
    document, to raise a writer share now rather than after delivery."""
    writer = _rel(role="Co-writer").signable_text()
    player = _rel(role="Performer").signable_text()
    assert "the writing, not only the performance" in writer
    assert "credited as a writer with a share" in writer
    assert "the writing, not only the performance" not in player


def test_it_is_explicitly_not_about_their_fee():
    """A session player asked to sign something by a studio they have never heard of
    assumes it is about money. It is not, and saying so is what makes it signable."""
    text = _rel().signable_text()
    assert "not about your fee" in text
    assert "between you and the person who booked you" in text


def test_it_is_short_enough_to_actually_read():
    """Four pages on a phone between takes is signed without reading, and a release
    signed without reading is the one a dispute unpicks first."""
    assert len(_rel().signable_text().splitlines()) < 45


def test_it_is_deterministic_and_shares_the_studios_jurisdiction():
    a, b = _rel().signable_text(), _rel().signable_text()
    assert a == b and document_digest(a) == document_digest(b)
    from chordential_oia import composer_agreement
    assert composer_agreement.governing_law() in a, (
        "two documents governed by different states is a fight about which one applies")


# ── the flow: the composer names them, they sign, the certificate knows ──────────────
@pytest.fixture()
def gated(tmp_path, monkeypatch):
    monkeypatch.setenv("CHORDENTIAL_DB", str(tmp_path / "contrib.db"))
    monkeypatch.setenv("CHORDENTIAL_ADMIN_TOKEN", "passphrase")
    for m in ("db", "campaigns", "app"):
        importlib.reload(importlib.import_module(f"chordential_oia.web.{m}"))
    from fastapi.testclient import TestClient
    from chordential_oia.web import app as app_mod
    with TestClient(app_mod.app) as c:
        yield c, app_mod


def _project_and_composer(app_mod):
    from chordential_oia.models import MusicDiscipline
    from chordential_oia.talent import Talent
    db = app_mod.db
    conn = db.connect()
    try:
        pid = conn.execute(
            "SELECT id FROM projects ORDER BY id LIMIT 1").fetchone()["id"]
        tid = db.insert_talent(conn, Talent(name="Dale Malleh", email="dale@example.com",
                                            disciplines=[MusicDiscipline.COMPOSITION]))
        return pid, tid, db.ensure_talent_portal_token(conn, tid)
    finally:
        conn.close()


def _name_one(c, token, pid, name="Ana Ruiz", role="Vocalist",
              email="ana@example.com"):
    return c.post(f"/creator/{token}/project/{pid}/contributor",
                  data={"name": name, "role": role, "email": email},
                  follow_redirects=False)


def test_the_composer_names_them_and_they_are_emailed(gated, monkeypatch):
    from chordential_oia import mailer
    sent = []
    monkeypatch.setattr(mailer, "mail_configured", lambda: True)
    monkeypatch.setattr(mailer, "send_email",
                        lambda to, subject, body, **kw: (sent.append((to, body))
                                                         or "sent"))
    c, app_mod = gated
    pid, _tid, token = _project_and_composer(app_mod)
    r = _name_one(c, token, pid)
    assert r.status_code == 303
    assert len(sent) == 1 and sent[0][0] == "ana@example.com"
    body = sent[0][1]
    assert "/contributor/" in body, "the mail must carry their signing link"
    assert "Dale Malleh" in body, "say who named them or it reads as spam"
    assert "not your fee" in body or "does not\nchange it" in body


def test_the_contributor_signs_without_an_account(gated):
    """They are not a user of this system and never will be — the link is the whole
    credential, and the admin gate must not meet them (it met a real client once)."""
    c, app_mod = gated
    pid, _tid, token = _project_and_composer(app_mod)
    _name_one(c, token, pid)
    conn = app_mod.db.connect()
    try:
        row = app_mod.db.list_contributors(conn, pid)[0]
    finally:
        conn.close()
    page = c.get(f"/contributor/{row['token']}")
    assert page.status_code == 200
    assert "Password or passphrase" not in page.text
    assert "CONTRIBUTOR RELEASE" in page.text

    r = c.post(f"/contributor/{row['token']}/sign",
               data={"typed_name": "Ana Ruiz", "signer_email": "ana@example.com",
                     "consent": "1"}, follow_redirects=False)
    assert r.status_code == 303
    assert "/admin/login" not in r.headers.get("location", "")
    conn = app_mod.db.connect()
    try:
        sig = app_mod.db.latest_contributor_signature(
            conn, row["id"], DOC_CONTRIBUTOR_RELEASE)
    finally:
        conn.close()
    assert sig is not None and sig["typed_name"] == "Ana Ruiz"
    assert sig["digest"] == document_digest(
        contributor_release.build_release(row).signable_text())


def test_consent_is_required(gated):
    c, app_mod = gated
    pid, _tid, token = _project_and_composer(app_mod)
    _name_one(c, token, pid)
    conn = app_mod.db.connect()
    try:
        row = app_mod.db.list_contributors(conn, pid)[0]
    finally:
        conn.close()
    c.post(f"/contributor/{row['token']}/sign",
           data={"typed_name": "Ana Ruiz", "consent": ""}, follow_redirects=False)
    conn = app_mod.db.connect()
    try:
        assert app_mod.db.latest_contributor_signature(
            conn, row["id"], DOC_CONTRIBUTOR_RELEASE) is None
    finally:
        conn.close()


def test_a_bad_token_is_not_found(gated):
    c, _app_mod = gated
    assert c.get("/contributor/nope").status_code == 404
    assert c.post("/contributor/nope/sign",
                  data={"typed_name": "X", "consent": "1"},
                  follow_redirects=False).status_code == 404


def test_a_signed_release_cannot_be_deleted(gated):
    """Evidence is not removed because it is inconvenient — the rule the signature table
    already follows."""
    c, app_mod = gated
    pid, _tid, token = _project_and_composer(app_mod)
    _name_one(c, token, pid)
    conn = app_mod.db.connect()
    try:
        row = app_mod.db.list_contributors(conn, pid)[0]
        assert app_mod.db.remove_contributor(conn, row["id"]) is True
    finally:
        conn.close()
    _name_one(c, token, pid, name="Sam Vale", email="sam@example.com")
    conn = app_mod.db.connect()
    try:
        row = app_mod.db.list_contributors(conn, pid)[0]
    finally:
        conn.close()
    c.post(f"/contributor/{row['token']}/sign",
           data={"typed_name": "Sam Vale", "consent": "1"}, follow_redirects=False)
    conn = app_mod.db.connect()
    try:
        assert app_mod.db.remove_contributor(conn, row["id"]) is False
        assert len(app_mod.db.list_contributors(conn, pid)) == 1
    finally:
        conn.close()


# ── the point of all of it: the certificate knows ────────────────────────────────────
def test_the_certificate_cannot_be_signed_while_a_release_is_outstanding(gated):
    """The whole reason this exists. Warranting to a buyer that nothing in the work needs
    anyone else's permission, while holding a list of people who have not given theirs,
    is the failure the chain of title is supposed to prevent."""
    from chordential_oia.web.project_routes import _delivery_view
    c, app_mod = gated
    pid, _tid, token = _project_and_composer(app_mod)
    conn = app_mod.db.connect()
    try:
        before = _delivery_view(conn, pid)
    finally:
        conn.close()
    assert before is not None and before["release_gaps"] == []
    signable_before = before["cert_signable"]
    assert signable_before is True, (
        "the certificate is not signable even before a contributor exists — this test "
        "would then pass without proving anything")

    _name_one(c, token, pid)
    conn = app_mod.db.connect()
    try:
        view = _delivery_view(conn, pid)
        row = app_mod.db.list_contributors(conn, pid)[0]
    finally:
        conn.close()
    assert [g["name"] for g in view["release_gaps"]] == ["Ana Ruiz"]
    assert view["cert_signable"] is False, (
        "the certificate is signable with an unsigned contributor on the project")

    c.post(f"/contributor/{row['token']}/sign",
           data={"typed_name": "Ana Ruiz", "consent": "1"}, follow_redirects=False)
    conn = app_mod.db.connect()
    try:
        after = _delivery_view(conn, pid)
    finally:
        conn.close()
    assert after["release_gaps"] == []
    assert after["cert_signable"] == signable_before, "signing did not unblock it"


def test_the_console_names_who_is_outstanding(gated):
    """"Some releases missing" is not actionable. Who, and how to chase them, is."""
    c, app_mod = gated
    pid, _tid, token = _project_and_composer(app_mod)
    _name_one(c, token, pid)
    c.post("/admin/login", data={"email": "", "password": "passphrase"},
           follow_redirects=False)
    page = c.get(f"/project/{pid}/delivery").text
    assert "release" in page and "Ana Ruiz" in page
    assert "cannot be signed until" in page


def test_the_release_is_not_emailed_as_a_composer_agreement(gated, monkeypatch):
    """A session player's receipt must name the document she signed.

    It borrowed the Composer Agreement's mail wholesale, so a cellist was sent "Your
    signed Composer Agreement" and the operator was told she was "now assignable" — she
    is not on the roster and cannot be assigned to anything. A receipt for a signature
    that names the wrong instrument is the honesty rule broken where it matters most.
    """
    from chordential_oia import mailer
    c, app_mod = gated
    pid, _tid, token = _project_and_composer(app_mod)
    _name_one(c, token, pid)
    conn = app_mod.db.connect()
    try:
        row = app_mod.db.list_contributors(conn, pid)[0]
    finally:
        conn.close()

    sent = []
    monkeypatch.setenv("CHORDENTIAL_OPERATOR_EMAIL", "jon@chordential.com")
    monkeypatch.setattr(mailer, "mail_configured", lambda: True)
    monkeypatch.setattr(mailer, "send_email",
                        lambda to, subject, body, **kw: (
                            sent.append((to, subject, body)) or "sent"))
    c.post(f"/contributor/{row['token']}/sign",
           data={"typed_name": "Ana Ruiz", "signer_email": "ana@example.com",
                 "consent": "1"}, follow_redirects=False)

    assert sent, "she signed a rights assignment and got no copy of it"
    for _to, subject, body in sent:
        assert "Composer Agreement" not in subject, f"wrong document named: {subject!r}"
        assert "Composer Agreement" not in body
        assert "now assignable" not in body, (
            "a contributor is not a roster creator and cannot be assigned")
    signer = [s for s in sent if s[0] == "ana@example.com"]
    operator = [s for s in sent if s[0] == "jon@chordential.com"]
    assert signer and "Contributor Release" in signer[0][1]
    assert operator and "Contributor Release" in operator[0][1]
    assert "not about your fee" in signer[0][2] or "not about your fee" in signer[0][2].lower()
