"""The public delivery sample — generated by the engine, never hand-typed.

The sample package a producer forwards to business affairs used to be 390 lines
of hand-authored HTML depicting eight documents the product generates. It had
drifted, and drifted in the one direction that costs us: it filed usage code
``VV`` on a campaign bed — the exact defect :mod:`chordential_oia.delivery`
documents having fixed, an assertion that performers appear on camera, which
nothing in this system knows. It also carried one conflated ``100%`` share where
the engine emits writer and publisher share separately, a hardcoded ``BMI`` for
every writer after the PRO became per-writer, and ``Logo`` in a column that only
takes PRO usage codes.

A music coordinator who reads ``VV`` on a bed understands it as a claim of an
on-camera vocal performance, and then doubts every other number on the page —
including the ones that are right. The document exists to be believed.

So the page is no longer written. It is *rendered*, from the same builders that
assemble a real client's ZIP, over an invented campaign. The seam is
``delivery._val``, which reads a plain dict exactly as it reads a database row,
so the fixture below needs no database and this module needs no session: the
highest-traffic public route must survive a Postgres blip.

Invented brands only, per the honesty rule — AURORA Outdoor Co. via Northlight
Creative, the same fiction the sample has always used. The signature block stays
unsigned on the client side: ``signing`` binds a signature to a hash of the exact
text signed, and depicting one that never happened would manufacture a record
under the one module whose whole purpose is that records are real.

Imports flow one way: ``app.py`` → ``public.py`` → here → ``delivery.py``.
"""

from __future__ import annotations

from typing import Any, Dict, List

from .. import delivery

# --------------------------------------------------------------------------- #
# The invented campaign. Plain dicts — the shape `delivery._val` reads.
# --------------------------------------------------------------------------- #

SAMPLE_CLIENT = "AURORA Outdoor Co."
SAMPLE_AGENCY = "Northlight Creative"
SAMPLE_CAMPAIGN = "Find Your Horizon"

PROJECT: Dict[str, Any] = {
    "id": 0,
    "client": SAMPLE_CLIENT,
    "need": SAMPLE_CAMPAIGN,
    "description": (
        "Brand anthem for a spring outdoor campaign — a :60 hero cut for broadcast "
        "and online, with :30 / :15 / :06 cutdowns and social verticals. Warm, "
        "unhurried, acoustic-led; no vocal."
    ),
}

# Chain of title. Every name here is invented; the PRO and publishing entity are
# carried per writer because that is how the engine accounts them (ADR-0031,
# ADR-0061) — a writer with no registered publishing entity leaves their share
# with the house rather than showing an unclaimed share that pays nobody.
ASSIGNMENTS: List[Dict[str, Any]] = [
    {"role": "Composer", "talent_name": "R. Alvarez",
     "talent_pro": "ASCAP", "talent_publisher": "Alvarez Songs"},
    {"role": "Composer", "talent_name": "M. Okonkwo",
     "talent_pro": "BMI", "talent_publisher": ""},
    {"role": "Engineer", "talent_name": "D. Sereno",
     "talent_pro": "", "talent_publisher": ""},
]

# The version ladder the review surface produced, in the shape delivery_json holds.
VERSIONS: List[Dict[str, Any]] = [
    {"n": 1, "label": "v1", "name": "FINDYOURHORIZON_ANTHEM_60_MASTER_v1"},
    {"n": 2, "label": "v2", "name": "FINDYOURHORIZON_ANTHEM_60_MASTER_v2"},
    {"n": 3, "label": "v3 FINAL", "name": "FINDYOURHORIZON_ANTHEM_60_MASTER_v3_FINAL"},
]

# What the operator confirmed, and who signs. The client half of the signature
# block is deliberately absent — see the module docstring.
LICENSE_CONFIRMED: Dict[str, Any] = {"by": "Jon Shipp", "date": "2026-03-18"}

# Per-cue identification, in the shape delivery_json['cue_meta'] holds. The engine
# leaves these blank by default and lets the agency's music coordinator fill them;
# the sample fills them because a sample of a fileable cue sheet that is not
# fileable demonstrates the wrong thing. Invented codes, like the campaign.
CUE_META: Dict[str, Dict[str, str]] = {
    SAMPLE_CAMPAIGN: {"duration": "1:00", "isrc": "US-CHD-26-00417",
                      "iswc": "T-931.005.417-2"},
    f"{SAMPLE_CAMPAIGN} — cutdowns": {"duration": "0:30 / 0:15 / 0:06",
                                      "isrc": "US-CHD-26-00418",
                                      "iswc": "T-931.005.417-2"},
}


def _project() -> Dict[str, Any]:
    return dict(PROJECT)


def sample_cue_sheet() -> List[delivery.CueRow]:
    """The cue sheet, from the engine. Never a table written by hand."""
    return delivery.build_cue_sheet(_project(), ASSIGNMENTS,
                                    delivery={"cue_meta": CUE_META})


def sample_manifest() -> List[delivery.ManifestRow]:
    """The deliverables manifest, including the version ladder."""
    return delivery.build_manifest(_project(), versions=VERSIONS)


def sample_certificate() -> delivery.ClearanceCertificate:
    """The clearance certificate — warranty, chain of title, grant, Content-ID.

    ``license_confirmed`` is passed so the grant reads as asserted rather than
    ``DRAFT — pending confirmation``: on a published sample, a draft watermark on
    the rights language would misrepresent the product in the other direction.
    """
    return delivery.build_clearance_certificate(
        _project(), ASSIGNMENTS,
        license_confirmed=LICENSE_CONFIRMED,
        certified_version="v3 FINAL",
        certified_date=LICENSE_CONFIRMED["date"],
    )


def sample_context() -> Dict[str, Any]:
    """Everything the public sample template renders, all of it engine-derived."""
    cert = sample_certificate()
    return {
        "client": SAMPLE_CLIENT,
        "agency": SAMPLE_AGENCY,
        "campaign": SAMPLE_CAMPAIGN,
        "cues": sample_cue_sheet(),
        "manifest": sample_manifest(),
        "cert": cert,
        "rights_text": delivery.rights_certificate_text(cert),
        "versions": VERSIONS,
    }
